_logging_pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5level} log_level=\"%level\" ${PID:- } --- [thread=\"%thread\", httpMethod=\"%X{httpMethod:-null}\", httpRequestURI=\"%X{httpRequestURI:-null}\", X-Request-ID=\"%X{requestId:-null}\"] [%15.15t] %-40.40logger{39} : %replace(%msg){'\r\n|\n', '\u2028'} %replace(%ex{full}){'\r\n|\n', '\u2028'}%nopex"
_logging_pattern_console: "${_logging_pattern}%n"
logging:
  pattern:
    console: ${_logging_pattern_console}

cloudflare:
  api:
    accountID: ${CLOUDFLARE_ACCOUNTID}
    key: ${CLOUDFLARE_KEY}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_USER_PASSWORD}
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: rabbitmq
    password: ${RABBITMQ_PASSWORD}
    port: 61613
    requested-heartbeat: 580
    username: ${RABBITMQ_USERNAME}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

app:
  environment:
    ALLOWED_ORIGINS:
      - ${ALLOWED_ORIGIN}
