name: Docker Build and Push

on:
  push:
    branches:
      - '*'
    tags:
      - 'release-[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.digitalocean.com
      REGISTRY_NAME: teamsphere
      REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Running Unit Tests
        run: |
          ./mvnw clean compile install

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_REGISTRY_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.REPOSITORY }}
          tags: |
            # For release tags (e.g., release-1.0.0)
            type=match,pattern=release-(.*),group=1
            type=match,pattern=release-(\d+.\d+).*,group=1
            type=match,pattern=release-(\d+.\d+).*,group=1
            
            # For branches (e.g., main -> main, feature/xyz -> feature-xyz)
            type=ref,event=branch
            
            # For pull requests (PR-123)
            type=ref,event=pr
      - name: Echo Tags
        run: |
          echo "Tags: ${{ steps.metadata.outputs.tags }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PROFILE=prod
            APP_VERSION= ${{ steps.metadata.outputs.tags }}

  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            ls -al


